name: PoixpixelCustom
version: 2.0.0-SNAPSHOT
main: com.poixpixelcustom.PoixpixelCustom
description: A Custom Plugin for Poixpixel
author: ahmadk953
api-version: '1.20'

# Dependencies
depend: [Vault]

# Commands
commands:
  explodingentity:
    description: "Spawn an explosive entity"
    usage: "/explodingentity [set/baby] [entity]"
    aliases: [ explosiveentity ]
    permission: poixpixelcustom.command.explodingentity
    permission-message: "You don't have permission to spawn an explosive cow"
  butterfly:
    description: "Toggle Butterfly particle effect"
    usage: "/butterfly"
    permission: poixpixelcustom.command.butterfly
  displayentity:
    aliases: [ de ]
    description: "Spawns a display entity"
    usage: "/displayentity [item/block/text] [block/item]"
    permission: poixpixelcustom.command.displayentity
  customitem:
    description: "Gives you a custom item"
    usage: "/customitem"
    permission: poixpixelcustom.command.customitem
  gui:
    description: "Opens a Custom GUI"
    usage: "/gui"
    permission: poixpixelcustom.command.gui

# Permissions
permissions:
  poixpixelcustom.command.explodingentity:
    default: true
  poixpixelcustom.explodingentity.use:
    default: true
  poixpixelcustom.laser.use:
    default: false

# Bstats
bStats:
  enabled: true
  serverUuid: ""
  logFailedRequests: false
  logSentData: false
  logResponseStatusText: false