name: PoixpixelCustom
version: 2.0.0-SNAPSHOT
main: com.poixpixelcustom.PoixpixelCustom
description: A Custom Plugin for Poixpixel
author: ahmadk953
api-version: '1.20'

# Bstats
bStats:
  enabled: true
  serverUuid: ""
  logFailedRequests: false
  logSentData: false
  logResponseStatusText: false