name: PoixpixelCustom
version: '${project.version}'
main: com.poixpixelcustom.PoixpixelCustom
api-version: 1.19
authors: [ ahmadk953 ]
description: A custom plugin made for Poixpixel
depend: [ Vault ]
softdepend: [ Essentials ]
commands:
  enrich:
    description: Makes you rich!
    usage: /<command>
    aliases: [ rich ]
  test-economy:
    discription: Gives you $1.05 when ran
    usage: /<command>
    aliases: [ money giveMoney ]
  test-permission:
    discription: Tests to see if you have the poixpixelcustom.awesome permission
    usage: /<command>
    aliases: [ amICool, coolOrNot ]
permissions:
  poixpixelcustom.enrich:
    description: Gives access to use the enrich command
    default: op
  poixpixelcustom.*:
    description: All commands
    default: op
  poixpixelcustom.awesome:
    discription: Awesome or not?
    default: op

