name: Maven Publish

on:
  push:
    branches: [ master ]
  release:
    types: [ created ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    strategy:
      matrix:
        java: [ "21" ]

    steps:
    - uses: actions/checkout@v4
    - name: Set up Eclipse Temurin
      uses: actions/setup-java@v4
      with:
        java-version: ${{ matrix.java }}
        java-package: jdk
        distribution: 'temurin'
        server-id: github
        settings-path: ${{ github.workspace }}

    - name: Cache Maven packages
      uses: actions/cache@v4
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2

    - name: Build with Maven
      run: mvn -B clean package

    - name: Publish to GitHub Packages Apache Maven
      run: mvn deploy -s $GITHUB_WORKSPACE/settings.xml -f github-pom.xml
      env:
        GITHUB_TOKEN: ${{ github.token }
