name: Deploy Java Package to JFrog Artifactory

on:
  release:
    types: [released]
  workflow_dispatch:
  push:
    branches: [master]
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Eclipse Temurin
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "21"
          java-package: jdk
          settings-path: ${{ github.workspace }}
      
      - name: Create Maven settings.xml
        run: |
          touch $HOME/.m2/settings.xml
          echo "${{ secrets.MAVEN_SETTINGS }}" > $HOME/.m2/settings.xml
      
      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Deploy
        run: mvn deploy -DskipTests
